## Write a Numpy program to compute the multiplication of two given matrixes

In [2]:
import numpy as np

In [4]:
a=np.array([[1,2,3,4,5],
            [1,2,3,4,5]])
b=np.array([[1,2,3,4,5],
            [1,2,3,4,5]])
c=a*b
c

array([[ 1,  4,  9, 16, 25],
       [ 1,  4,  9, 16, 25]])

## Write a NumPy program to compute the determinant of a given square array

In [11]:
a=np.array([
            [1,2],
            [3,4]])


In [12]:
b=np.linalg.det(a)
print(b)

-2.0000000000000004


## Write a NumPy program to compute the cross product of two given vectors

In [13]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [14]:
result=np.cross(a, b)
print(result)

[-3  6 -3]


## Write a NumPy program to compute the condition number of a given matrix

In [22]:
a = np.array([
             [1, 0, -1], 
             [0, 1, 0], 
             [1, 0, 1]])

In [24]:
b=np.linalg.cond(a)
b

1.4142135623730951

## Write a NumPy program to compute the inverse of a given matrix

In [19]:
a = np.array([
             [1,2],
             [3,4]])

In [20]:
b=np.linalg.inv(a)

In [21]:
b

array([[-2. ,  1. ],
       [ 1.5, -0.5]])